jQuery.extend(Drupal.settings, {
  basePath: "/",
  pathPrefix: "",
  ajaxPageState: {
    theme: "black_hole",
    theme_token: "V-wejzgE_41RiP1NbAQMCSWKXCxNw8-gopshI1pPr9c",
    js: {
      "misc/jquery.js": 1,
      "misc/jquery.once.js": 1,
      "misc/drupal.js": 1,
      "public://languages/hr_B2HHOlUFDpz_9u9tRYTUYab4TsnQlB_Jvoy3k6sulWg.js": 1,
      "sites/all/libraries/colorbox/jquery.colorbox-min.js": 1,
      "sites/all/modules/colorbox/js/colorbox.js": 1,
      "sites/all/modules/colorbox/styles/default/colorbox_style.js": 1,
      "sites/all/modules/colorbox/js/colorbox_load.js": 1,
      "sites/all/modules/colorbox/js/colorbox_inline.js": 1,
      "sites/all/themes/black_hole//js/jquery.hoverIntent.minified.js": 1,
      "sites/all/themes/black_hole//js/dropdown.js": 1,
    },
    css: {
      "modules/system/system.base.css": 1,
      "modules/system/system.menus.css": 1,
      "modules/system/system.messages.css": 1,
      "modules/system/system.theme.css": 1,
      "sites/all/modules/date/date_api/date.css": 1,
      "sites/all/modules/date/date_popup/themes/datepicker.1.7.css": 1,
      "modules/field/theme/field.css": 1,
      "modules/node/node.css": 1,
      "modules/search/search.css": 1,
      "modules/user/user.css": 1,
      "sites/all/modules/views/css/views.css": 1,
      "sites/all/modules/ckeditor/ckeditor.css": 1,
      "sites/all/modules/colorbox/styles/default/colorbox_style.css": 1,
      "sites/all/modules/ctools/css/ctools.css": 1,
      "sites/all/modules/panels/css/panels.css": 1,
      "sites/all/modules/panels/plugins/layouts/flexible/flexible.css": 1,
      "public://ctools/css/b468c366187032e8f8f73486884f45ca.css": 1,
      "sites/all/themes/black_hole/css/style-bh.css": 1,
      "sites/all/themes/black_hole/css/protostar.css": 1,
      "sites/all/themes/black_hole/_custom/custom-style.css": 1,
      "sites/all/themes/black_hole/css/round.css": 1,
      "sites/all/themes/black_hole/css/print.css": 1,
      "sites/all/themes/black_hole/css/ie6.css": 1,
      "sites/all/themes/black_hole/css/ie7.css": 1,
    },
  },
  colorbox: {
    opacity: "0.85",
    current: "{current} of {total}",
    previous: "\u00ab Prev",
    next: "Next \u00bb",
    close: "Close",
    maxWidth: "98%",
    maxHeight: "98%",
    fixed: true,
    mobiledetect: true,
    mobiledevicewidth: "480px",
  },
});

var ccm_cfg = {
  pth: "http://www.moonmodule.com/cs/",
  fn: "ccm_v1.swf",
  lg: "en",
  hs: 1,
  tf: "24hr",
  scs: 1,
  df: "std",
  dfd: 0,
  tc: "FFFFFF",
  bgc: "000000",
  mc: "000000",
  fw: 102,
  fh: 151,
  js: 0,
  msp: 0,
  u: "cc",
};
